export const mockupData = {
    pageInfo: {
      hasNextPage: true,
      hasPreviousPage: false,
    },
    totalCount: 125,
    items: [
      {
        id: "61e4d8bb1b28005b0fd9545b",
        name: "Yến Đẹp Dáng Bổ Thận",
        description:
          "Đây là những tổ yến thô được chọn lọc theo tỷ lệ kim cương (100 tổ chọn 1 tổ). Tổ hình tròn, dày, rất ít lông, thường có khoảng 2-4 vị trí có lông, không có bụng, nhiều sợi. Thời gian làm sạch giảm đến 50% so với yến thô thông thường. Tỷ lệ thất thoát khoảng 20% đối với những người không chuyên.",
        price: 4000000,
        discount: 200000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Nói đến yến thì chúng có rất nhiều công dụng cũng như có thể dùng để chế biến thành nhiều món ăn khác nhau như: yến sào chưng đường phèn, yến sào nấu gà, yến sào gà ác, cháo yến sào… và đó. là nhiều món ăn khác có thể dùng để chế biến yến mạch. Đặc biệt khi sử dụng yến mạch để chế biến các món ăn sẽ tỏa ra mùi hương rất thơm ngon, đồng thời chứa nhiều chất dinh dưỡng cần thiết cho con người, giúp cơ thể bạn trở nên trẻ đẹp, tràn đầy năng lượng. tuổi thọ, sức đề kháng cao để phòng tránh các bệnh nguy hiểm.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 6,
        totalViews: 39,
        totalPurchases: 0,
        mass: "50g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.896Z",
        updatedAt: "2023-05-17T13:25:58.389Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/HH11.jpg",
        maxQuantity: 100,
        ratingAvg: 1.0694444444444444,
      },
      {
        id: "61e4d8bb1b28005b0fd9545d",
        name: "Yến Khoẻ Mạnh Bổ Thận",
        description:
          "Tổ yến đã qua chế biến của Hồng Gia Yến thích hợp với những người ít chế biến, sau khi mua về có thể sử dụng ngay. Để sử dụng tổ yến tinh chế này, bạn chỉ cần ngâm tổ yến từ 30 – 45 phút, sau đó rửa sạch lại.",
        price: 1000000,
        discount: 700000,
        ingredient: "100% Yến sào (trắng) và các phụ gia",
        uses: "Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 16,
        totalPurchases: 0,
        mass: "40g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.898Z",
        updatedAt: "2023-06-25T07:54:31.338Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/HH13.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
      {
        id: "61e4d8bb1b28005b0fd95461",
        name: "Yến Khoẻ Mạnh Sáng Mắt",
        description:
          "Tổ yến nguyên chất 100% được khai thác tại nhà yến chuyên nghiệp. Được chọn lọc theo tỉ lệ “vương miện” – điểm 10 cho chất lượng. Được các nghệ nhân nuôi chim yến lành nghề, giàu kinh nghiệm đảm nhận. Không sử dụng chất bảo quản, tẩm ướp, phụ gia. Đặc điểm: Màu trắng ngà, tổ yến to dày, nhiều sợi, trọng lượng mỗi tổ> 10g / tổ.",
        price: 8000000,
        discount: 100000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Nói đến yến thì chúng có rất nhiều công dụng cũng như có thể dùng để chế biến thành nhiều món ăn khác nhau như: yến sào chưng đường phèn, yến sào nấu gà, yến sào gà ác, cháo yến sào… và đó. là nhiều món ăn khác có thể dùng để chế biến yến mạch. Đặc biệt khi sử dụng yến mạch để chế biến các món ăn sẽ tỏa ra mùi hương rất thơm ngon, đồng thời chứa nhiều chất dinh dưỡng cần thiết cho con người, giúp cơ thể bạn trở nên trẻ đẹp, tràn đầy năng lượng. tuổi thọ, sức đề kháng cao để phòng tránh các bệnh nguy hiểm.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 2,
        totalViews: 18,
        totalPurchases: 0,
        mass: "70g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.898Z",
        updatedAt: "2023-06-08T09:46:25.676Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/XT12.jpg",
        maxQuantity: 100,
        ratingAvg: 4,
      },
      {
        id: "61e4d8bb1b28005b0fd95467",
        name: "Yến Tăng Chiều Cao Bổ Thận",
        description:
          "Tổ yến đã qua chế biến của Hồng Gia Yến thích hợp với những người ít chế biến, sau khi mua về có thể sử dụng ngay. Để sử dụng tổ yến tinh chế này, bạn chỉ cần ngâm tổ yến từ 30 – 45 phút, sau đó rửa sạch lại.",
        price: 8000000,
        discount: 100000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Nói đến yến thì chúng có rất nhiều công dụng cũng như có thể dùng để chế biến thành nhiều món ăn khác nhau như: yến sào chưng đường phèn, yến sào nấu gà, yến sào gà ác, cháo yến sào… và đó. là nhiều món ăn khác có thể dùng để chế biến yến mạch. Đặc biệt khi sử dụng yến mạch để chế biến các món ăn sẽ tỏa ra mùi hương rất thơm ngon, đồng thời chứa nhiều chất dinh dưỡng cần thiết cho con người, giúp cơ thể bạn trở nên trẻ đẹp, tràn đầy năng lượng. tuổi thọ, sức đề kháng cao để phòng tránh các bệnh nguy hiểm.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 5,
        totalPurchases: 0,
        mass: "50g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.898Z",
        updatedAt: "2023-06-16T10:26:06.911Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/HH13.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
      {
        id: "61e4d8bb1b28005b0fd9546d",
        name: "Yến Đẹp Dáng Số 1",
        description:
          "Tổ yến là một loại thực phẩm chứa nhiều chất dinh dưỡng cần thiết cho cơ thể con người. Với 18 loại axit amin và nhiều chất dinh dưỡng khác, tổ yến có giá trị cao và được bán với giá khá đắt ngoài thị trường.",
        price: 1000000,
        discount: 700000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Nói đến yến thì chúng có rất nhiều công dụng cũng như có thể dùng để chế biến thành nhiều món ăn khác nhau như: yến sào chưng đường phèn, yến sào nấu gà, yến sào gà ác, cháo yến sào… và đó. là nhiều món ăn khác có thể dùng để chế biến yến mạch. Đặc biệt khi sử dụng yến mạch để chế biến các món ăn sẽ tỏa ra mùi hương rất thơm ngon, đồng thời chứa nhiều chất dinh dưỡng cần thiết cho con người, giúp cơ thể bạn trở nên trẻ đẹp, tràn đầy năng lượng. tuổi thọ, sức đề kháng cao để phòng tránh các bệnh nguy hiểm.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 5,
        totalPurchases: 0,
        mass: "50g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.898Z",
        updatedAt: "2023-06-16T16:36:13.694Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/XT22.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
      {
        id: "61e4d8bb1b28005b0fd95473",
        name: "Yến Nhanh Nhẹn Thông Minh",
        description:
          "Tổ yến là một loại thực phẩm bổ dưỡng mà thiên nhiên ban tặng cho con người, nó có độ khô rất cao và chứa nhiều chất dinh dưỡng cần thiết cho cơ thể con người. Nhưng việc bảo quản loại thực phẩm này vô cùng khó khăn, nếu không biết cách bảo quản sẽ làm hỏng hoặc giảm chất lượng của sản phẩm.",
        price: 1000000,
        discount: 300000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Nói đến yến thì chúng có rất nhiều công dụng cũng như có thể dùng để chế biến thành nhiều món ăn khác nhau như: yến sào chưng đường phèn, yến sào nấu gà, yến sào gà ác, cháo yến sào… và đó. là nhiều món ăn khác có thể dùng để chế biến yến mạch. Đặc biệt khi sử dụng yến mạch để chế biến các món ăn sẽ tỏa ra mùi hương rất thơm ngon, đồng thời chứa nhiều chất dinh dưỡng cần thiết cho con người, giúp cơ thể bạn trở nên trẻ đẹp, tràn đầy năng lượng. tuổi thọ, sức đề kháng cao để phòng tránh các bệnh nguy hiểm.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 1,
        totalPurchases: 0,
        mass: "10g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.898Z",
        updatedAt: "2022-12-28T01:40:01.700Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/NT2.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
      {
        id: "61e4d8bb1b28005b0fd95475",
        name: "Yến Nhanh Nhẹn Bổ Gan",
        description:
          "Tổ yến nguyên chất 100% được khai thác tại nhà yến chuyên nghiệp. Được chọn lọc theo tỉ lệ “vương miện” – điểm 10 cho chất lượng. Được các nghệ nhân nuôi chim yến lành nghề, giàu kinh nghiệm đảm nhận. Không sử dụng chất bảo quản, tẩm ướp, phụ gia. Đặc điểm: Màu trắng ngà, tổ yến to dày, nhiều sợi, trọng lượng mỗi tổ> 10g / tổ.",
        price: 2000000,
        discount: 400000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 0,
        totalPurchases: 0,
        mass: "50g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.898Z",
        updatedAt: "2022-01-17T02:47:23.898Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/XT12.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
      {
        id: "61e4d8bb1b28005b0fd9547f",
        name: "Yến Nhanh Nhẹn Sáng Mắt",
        description:
          "Tổ yến nguyên chất 100% được khai thác tại nhà yến chuyên nghiệp. Được chọn lọc theo tỉ lệ “vương miện” – điểm 10 cho chất lượng. Được các nghệ nhân nuôi chim yến lành nghề, giàu kinh nghiệm đảm nhận. Không sử dụng chất bảo quản, tẩm ướp, phụ gia. Đặc điểm: Màu trắng ngà, tổ yến to dày, nhiều sợi, trọng lượng mỗi tổ> 10g / tổ.",
        price: 5000000,
        discount: 100000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Nói đến yến thì chúng có rất nhiều công dụng cũng như có thể dùng để chế biến thành nhiều món ăn khác nhau như: yến sào chưng đường phèn, yến sào nấu gà, yến sào gà ác, cháo yến sào… và đó. là nhiều món ăn khác có thể dùng để chế biến yến mạch. Đặc biệt khi sử dụng yến mạch để chế biến các món ăn sẽ tỏa ra mùi hương rất thơm ngon, đồng thời chứa nhiều chất dinh dưỡng cần thiết cho con người, giúp cơ thể bạn trở nên trẻ đẹp, tràn đầy năng lượng. tuổi thọ, sức đề kháng cao để phòng tránh các bệnh nguy hiểm.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 0,
        totalPurchases: 0,
        mass: "10g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.899Z",
        updatedAt: "2022-01-17T02:47:23.899Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/XT12.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
      {
        id: "61e4d8bb1b28005b0fd9547b",
        name: "Yến Khoẻ Mạnh Bổ Thận",
        description:
          "Tổ yến đã qua chế biến của Hồng Gia Yến thích hợp với những người ít chế biến, sau khi mua về có thể sử dụng ngay. Để sử dụng tổ yến tinh chế này, bạn chỉ cần ngâm tổ yến từ 30 – 45 phút, sau đó rửa sạch lại.",
        price: 2000000,
        discount: 500000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 0,
        totalPurchases: 0,
        mass: "60g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.898Z",
        updatedAt: "2022-01-17T02:47:23.898Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/HH13.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
      {
        id: "61e4d8bb1b28005b0fd9548b",
        name: "Yến Nhanh Nhẹn Bổ Thận",
        description:
          "Tổ yến là một loại thực phẩm chứa nhiều chất dinh dưỡng cần thiết cho cơ thể con người. Với 18 loại axit amin và nhiều chất dinh dưỡng khác, tổ yến có giá trị cao và được bán với giá khá đắt ngoài thị trường.",
        price: 5000000,
        discount: 200000,
        ingredient: "100% Yến sào (trắng)",
        uses: "Nói đến yến thì chúng có rất nhiều công dụng cũng như có thể dùng để chế biến thành nhiều món ăn khác nhau như: yến sào chưng đường phèn, yến sào nấu gà, yến sào gà ác, cháo yến sào… và đó. là nhiều món ăn khác có thể dùng để chế biến yến mạch. Đặc biệt khi sử dụng yến mạch để chế biến các món ăn sẽ tỏa ra mùi hương rất thơm ngon, đồng thời chứa nhiều chất dinh dưỡng cần thiết cho con người, giúp cơ thể bạn trở nên trẻ đẹp, tràn đầy năng lượng. tuổi thọ, sức đề kháng cao để phòng tránh các bệnh nguy hiểm.",
        preservation: "Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp",
        expiryDate: "02 năm kể từ ngày sản xuất",
        totalRatings: 0,
        totalViews: 0,
        totalPurchases: 0,
        mass: "30g",
        origin: "Việt Nam",
        createdAt: "2022-01-17T02:47:23.899Z",
        updatedAt: "2022-01-17T02:47:23.899Z",
        category: null,
        owner: {
          fullName: "Admin12",
        },
        featuredImage: "src/assets/products/XT22.jpg",
        maxQuantity: 100,
        ratingAvg: 0,
      },
    ],
}
